// TODO: ADD INTERNALIZATION I18 to errors
export default {
  en: {
    INVALID_COORDINATES: 'INVALID COORDINATES',
    BREAKING_OFFICECALCULATION: 'UNEXPECTED OFFICE DATA',
    NO_SUPPLIER_FOUND: 'NO SUPPLIER FOUND'
  }
}
